// Dynamic loader untuk konten HTML materi sehingga tidak membengkakkan bundle utama
export const materialHtmlLoaders: Record<string, () => Promise<{ default: string }>> = {
  eksponensial: () => import("./eksponensial.html?raw"),
  sppl: () => import("./sppl.html?raw"),
  "fungsi-kuadrat": () => import("./fungsi-kuadrat.html?raw"),
  statistika: () => import("./statistika.html?raw"),
  "barisan-deret": () => import("./barisan-deret.html?raw"),
  "transformasi-fungsi": () => import("./transformasi-fungsi.html?raw"),
  matriks: () => import("./matriks.html?raw"),
  vektor: () => import("./vektor.html?raw"),
  lingkaran: () => import("./lingkaran.html?raw"),
  "busur-dan-juring-lingkaran": () => import("./lingkaran.html?raw"),
  trigonometri: () => import("./trigonometri.html?raw"),
  kombinatorika: () => import("./kombinatorika.html?raw"),
  peluang: () => import("./peluang.html?raw"),
  "komposisi-fungsi-dan-invers": () => import("./komposisi-fungsi-dan-invers.html?raw"),
  polinomial: () => import("./polinomial.html?raw"),
  "fungsi-pemodelan": () => import("./fungsi.html?raw"),
  "transformasi-geometri": () => import("./transformasi-geometri.html?raw"),
  "irisan-kerucut": () => import("./irisan-kerucut.html?raw"),
  "bilangan-kompleks": () => import("./bilangan-kompleks.html?raw"),
  limit: () => import("./limit.html?raw"),
  turunan: () => import("./turunan.html?raw"),
  integral: () => import("./integral.html?raw"),
  "teori-bilangan": () => import("./teori-bilangan.html?raw"),
};
